### SubmitTranslationRequest Command
POST http://localhost:3100/
Content-Type: application/json

{
"command": "SubmitTranslationRequest",
  "payload": {
     "text" : "test",
     "translationId" : ""
  }
}



